name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Laboratorium 7
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Skonfigurowanie dockera + buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      # Konfiguracja cachowania
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ${{secrets.DOCKER_HUB_USERNAME}}/lab6
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # Logowanie do Dockerhuba
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      # Zbudowanie i wypchniecie obrazu na Dockerhuba
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/lab6:latest
          cache-to: type=registry,ref=${{secrets.DOCKER_HUB_USERNAME}}/lab6:latest,mode=max
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          context: .
          push: true
          tags: |
            ${{secrets.DOCKER_HUB_USERNAME}}/lab6:latest
      # Przenies cache'a
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
